version: 0.0
os: linux
files:
  - source: /project-demo.jar
    destination: /home/ec2-user/demo-app/
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

